scrape: # Do not change these
  url: "https://documents.gov.lk/view/extra-gazettes/egz.html"

output: # Do not change these
  metadata_dir: "meta_data"
  years_json: "meta_data/years.json"
  doc_metadata_json: "meta_data/doc_metadata.json"
  upload_results_json: "upload_results/upload_results" 
  download_metadta_json: "meta_data/download_metadata.json"

archive: # Change on your preference
  archive_location: "path-to-your-local-archive-location" # Local archive location
  archive_base_url: "your-archive-repo-base-url"
  force_download_base_url: "your-rawgithubusercontent-base-url"

credentials: # Change on your preference
  divert_deepseek_api_key: your-deepseek-divert-api-key-from-bijira # Set your key
  divert_url_deep_seek: your-deepseek-divert-url-from-bijira # Set your URL
  
db_credentials:
  mongo_db_uri: your-mongodb-cloud-credentials-uri # Set your mongodb cloud credentials uri

